# Uncomment the next line to define a global platform for your project
use_frameworks!
platform :ios, '9.0'

target 'PageMenuDemoStoryboard' do
  pod 'PageMenu', :path => '../'

  target 'PageMenuDemoStoryboardTests' do
    inherit! :search_paths
    # Pods for testing
  end

end


